### PR TITLE
enable 2048mb graphics

### PR DESCRIPTION
**Pull request by ToonvanStrijp**
I edited the config.plist to support full capacity of the intel UHD630.

I found this repo: [https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave) and saw that it was working with 2048mb of memory

### CODE REVIEW

**Comment by bavariancake** [comment]
Yay, first PR! Thanks!

I hope this will/may improve IGPU performance a little.

We should watch stability with this patch in place to make sure this doesn't have any downsides.

Is there a way to monitor IGPU memory usage and benchmark FPS? I wonder why Apple chose to limit IGPU RAM to 1536MB, since this memory is only allocated if needed. Perhaps it was to limit the amount of memory taken up on 8GB MacBooks, or maybe they didn't see a performance improvement. Would be nice to add some tests/results to the readme.

Will merge when we have some test results on stability/performance. I'll start using this change for now.

**Comment by erenatas** [comment]
I think you should only add the part that's related to iGPU. Your commit has unnecessary lines

**Comment by ToonvanStrijp** [comment]
@erenatas Ow you're right. I thought I only pushed the changes. Will fix this ;).

**Comment by bavariancake** [comment]
@ToonvanStrijp - waiting for you provide an updated PR and testing info.

**Comment by bavariancake** [comment]
@ToonvanStrijp - ping.

**Comment by ToonvanStrijp** [comment]
@bavariancake heey sorry for my late response. But due to work I wasn't able to fix anything yet, I won't he able to do it upcoming weeks. Sorry for that.

**Comment by ToonvanStrijp** [comment]
@bavariancake can we close this issue since you force pushed?

**Comment by ToonvanStrijp** [comment]
@bavariancake Also do you have any other task that I could help with? I would like to do something to get a better battery performance but I'm fairly new to all this stuff so would like some directions.

**Pull request closed without merging**
